3.1 blablabla
EstandaresDeCalidadSW23/materia pull request #24
Opened 2023-09-09 19:06 UTC by bcisneros

2023-09-09 19:13 UTC, CarlosMoriel requested changes

2023-09-09 19:13 UTC, CarlosMoriel commented on README.md
> +
No debe quedar vacia esta linea

2023-09-09 19:13 UTC, CarlosMoriel commented on README.md
> +[Ver presentacion](3-1-iso-9000.txt)
Test

2023-09-09 19:15 UTC, CarlosMoriel requested changes

2023-09-09 19:15 UTC, CarlosMoriel commented on 3-1-iso-9000.txt
> +Here is the content of my presentation about ISO-9000
```suggestion
Here's  the content of my presentation about ISO-9000
```

2023-09-09 19:16 UTC, bcisneros commented on README.md
> +
Done

2023-09-09 19:18 UTC, CarlosMoriel approved these changes

2023-09-10 23:00 UTC, bcisneros commented
Closing this PR due is just an example

2023-09-10 23:00 UTC, closed without merging